<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RollForward>LatestMajor</RollForward>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ShopManagerMini</RootNamespace>
    <AssemblyName>ShopManagerMini</AssemblyName>
  </PropertyGroup>
</Project>
